const level1 = new Level(
  [new Chicken(), new Chicken(), new Chicken(), new Endboss()],
  [new Cloud()],
  [
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
  ],
  [
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
    new Bottles(),
  ],
  6,
  863
);
